

 <form action="<?php echo $this->baseUrl("perfil/gravar");?>" method="post">
      <input type="hidden" value="<?php echo $this->row['PERFIL_IN_ID']?>" name="PERFIL_IN_ID" />
      <div class="form-group">
          <label>Perfil:</label>
          <input class="form-control" type="text" name="PERFIL_ST_DESCRICAO" value="<?php echo $this->row['PERFIL_ST_DESCRICAO'];?>" />
     </div>
     <div class="form-group">
          <button class="btn btn-success" type="submit">Salvar<span class="glyphicon glyphicon-save"></span></button>
     </div>
</form>
