   <div class="page-header"><h3 class="text-center">Lista de Perfis</h3></div>
      <div  class="col-md-4">
         <a class="btn btn-warning" href ="<?php echo $this->baseUrl("/perfil/formulario")?>" id="modal-formulario-perfil" data-toggle="modal" data-target="#myModal" data-remote="false">Novo Perfil</a>
      </div>
      <br />    
      <br />

      <table class="table table-bordered table-hover">
            <tr class="text-center info">
             <td>Ações</td>
                <td>ID</td>
                <td>Nome</td>
                </tr>
        <?php if(sizeof($this->row)): ?>
            <?php foreach($this->row as $perfil){ ?>
            <tr>
                <td class="text-center">
                    <a class="btn btn-primary" title="Editar" href="<?php echo $this->baseUrl("perfil/formulario/PERFIL_IN_ID/").$this->escape($perfil->PERFIL_IN_ID)?>"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-danger" title="Excluir" href="<?php echo $this->baseUrl("perfil/excluir/PERFIL_IN_ID/").$this->escape($perfil->PERFIL_IN_ID)?>"><span class="glyphicon glyphicon-remove"></span></a> 
                </td>
                <td class="text-center"><?php echo $this->escape($perfil->PERFIL_IN_ID); ?></td>
                <td class="text-center"><?php echo $this->escape($perfil->PERFIL_ST_DESCRICAO); ?></td>
            </tr>    
                <?php } ?>
            
            </table>
        <?php else: ?>
            <li>Nenhum Perfil cadastrado.</li>
        <?php endif; ?>
        </ul>
 <script>
  $(function(){
	  $("#myModal").on("show.bs.modal", function(e) {
		    var link = $(e.relatedTarget);
		    $(this).find(".modal-body").load(link.attr("href"));
		});
  });
 </script>