<?php echo $this->doctype(); ?>
<html>
<head>
    	<?php echo $this->headMeta()->setHttpEquiv('Content-Type', 'text/html;charset=utf-8');?>
   	    <?php echo $this->headScript()->setFile("/assets/js/jquery-2.1.4.js"); ?>
        <?php echo $this->headScript()->appendFile("/assets/js/jquery.maskMoney.js"); ?>
        <?php echo $this->headScript()->appendFile("/assets/start-bootstrap/dist/js/sb-admin-2.js"); ?>
        <?php echo $this->headScript()->appendFile("/assets/js/jquery.number.min.js"); ?>
        <?php echo $this->headScript()->appendFile("/assets/js/jquery.maskedinput.min.js"); ?>
        <?php echo $this->headScript()->appendFile("/assets/js/mascaras.js"); ?>
        <?php echo $this->headScript()->appendFile("/assets/js/Chart.min.js"); ?>
        <!-- Morris Charts JavaScript -->
        <?php echo $this->headScript()->appendFile("/assets/start-bootstrap/bower_components/raphael/raphael-min.js"); ?>
         <!-- Metis Menu -->
        <?php echo $this->headScript()->appendFile("/assets/start-bootstrap/bower_components/metisMenu/dist/metisMenu.min.js"); ?>
        <!-- Custom Theme JavaScript -->
         <?php echo $this->headScript()->appendFile("/assets/start-bootstrap/dist/js/sb-admin-2.js"); ?>
        
        <?php echo $this->headScript()->appendFile("/assets/bootstrap/js/bootstrap.js"); ?>
        <?php echo $this->headLink()->setStylesheet("/assets/bootstrap/css/bootstrap.css"); ?>
        
        <?php echo $this->headLink()->setStylesheet("/assets/start-bootstrap/bower_components/metisMenu/dist/metisMenu.min.css"); ?>
        <?php echo $this->headLink()->setStylesheet("/assets/css/css.css"); ?>
        <?php echo $this->headLink()->setStylesheet("/assets/start-bootstrap/dist/css/sb-admin-2.css"); ?>
        <?php echo $this->headLink()->setStylesheet("/assets/start-bootstrap/bower_components/morrisjs/morris.css"); ?>
        <?php echo $this->headLink()->setStylesheet("/assets/start-bootstrap/bower_components/font-awesome/css/font-awesome.min.css"); ?>
        
        <!-- collor Picker  -->
        <script src='<?php echo $this->baseUrl('assets/color-picker/spectrum.js')?>'></script>
        <link rel='stylesheet' href='<?php echo $this->baseUrl('assets/color-picker/spectrum.css')?>' />
    </head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->baseUrl("/")?>">Agenda de Contas</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i>Perfil do Usuário</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                    </li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i>Perfil do Usuário</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Menu</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Second Level Item</a>
                            </li>
                            <li>
                                <a href="#">Second Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Item</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Item</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Item</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Item</a>
                                    </li>
                                </ul>
                                <!-- /.nav-third-level -->
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                     <li>
                        <a href="#"><i class="fa fa-user fa-fw"></i>Usuários<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->baseUrl("usuario/formulario")?>">Cadastro de Usuários</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl("usuario/index")?>">Lista de Usuários</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i>Contas<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->baseUrl("conta/formulario");?>">Cadastro de Contas</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl("conta/index ")?>">Lista de Contas</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i>Categorias<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->baseUrl("categoria/formulario")?>">Cadastro de Categorias</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl("categoria/index")?>">Lista de Categorias</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-money fa-fw"></i>Movimentação Financeira<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->baseUrl("mov-financeiro/formulario")?>">Novo Movimento Financeiro</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->baseUrl("mov-financeiro/index")?>">Lista de Movimentos Financeiros</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i>Bancos<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->baseUrl("banco/formulario")?>">Cadastro de Bancos</a>
                            </li>
                            <li>
                                <a href="<?php  echo $this->baseUrl("banco/index")?>">Lista de Bancos</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i>Agências<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="<?php echo $this->baseUrl("agencia/formulario")?>">Cadastro de Agências</a>
                            </li>
                            <li>
                                <a href="<?php  echo $this->baseUrl("agencia/index")?>">Lista de Agências</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                  </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
    <div id="wrapper">
         <div id="page-wrapper">
                  <br />

                  <?php echo $this->layout()->content; ?>

         </div>
         <!-- /#page-wrapper -->
    
    </div>
    <!-- /#wrapper -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-center">Modal Header</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<!--         <footer class="footer"> -->
<!--   <div class="container"> -->
<!--    <h3 class="text-muted align-center">Teste</h3> -->
<!--   </div> -->
<!--  </footer> -->
</body>
</html>