  <div class="page-header"><h1 align="center">Listagem de Contas<h1></div>
        <div class="col-lg-4">
         <a class="btn btn-warning" href="<?php echo $this->baseUrl("conta/formulario")?>">
            Cadastrar Conta
            <span class="glyphicon glyphicon-plus"></span>
         </a>
        </div> 
        <br />    
        <br />           
               
            <table class="table table-bordered table-hover">
            
            <tr class="text-center success">
             <td><b>Ações</b></td>
                <td><b>ID</b></td>
                <td><b>Nome</b></td>
                <td><b>Saldo</b></td>
                </tr>
        <?php if(sizeof($this->paginator)): ?>
            <?php foreach($this->paginator as $conta){ ?>
            <tr>
                <td class="text-center">
                    <a class="btn btn-primary" title="Editar" href="<?php echo $this->baseUrl("conta/formulario/BANCO_IN_ID/").$this->escape($conta->CON_IN_ID)?>"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-danger" title="Excluir" href="<?php echo $this->baseUrl("conta/excluir/BANCO_IN_ID/").$this->escape($conta->CON_IN_ID)?>"><span class="glyphicon glyphicon-remove"></span></a></td>
                <td class="text-center"><?php echo $this->escape($conta->CON_IN_ID); ?></td>
                <td class="text-center"><?php echo $this->escape($conta->CON_ST_DESCRICAO); ?></td>
                <td class="text-center"><?php echo $this->escape($conta->CON_DBL_SALDO); ?></td>
            </tr>    
                <?php } ?>
            
            </table>
        <?php else: ?>
            <li>Nenhuma conta encontrada.</li>
        <?php endif; ?>
        </ul>
        <?php echo $this->paginator; ?>
