<div class="col-md-12">
<form role="form" action="<?php echo $this->baseUrl("mov-financeiro/gravar")?>" method="POST">
<div class="panel panel-default">
<div class="panel-heading"><h3 class="text-center">Formulário Movimento Financeiro</h3></div>
<div class="panel-body">  
        <div class="col-md-3">
            <div class="form-group">
               <label for="MOV_CH_TIPO">Tipo de Movimento</label>
               <select name="MOV_CH_TIPO" id="input-tipo" class="form-control">
                <option value="D" <?php echo $this->row['MOV_CH_TIPO']=='D'?'selected':""?>>Débito</option>
                <option value="C" <?php echo $this->row['MOV_CH_TIPO']=='C'?'selected':""?>>Crédito</option>
            </select>
            </div>
            <div class="form-group" id="div-categoria">
               <label for="CAT_IN_ID">Categoria</label>
               <select name="CAT_IN_ID" class="form-control">
                    <?php foreach ($this->aCategoria as $categoria):?>
                    <option value="<?php echo $categoria['CAT_IN_ID']?>" style="background-color:<?php echo $categoria['CAT_ST_IDENTIFICADOR']?>;" <?php echo $this->row['CAT_IN_ID'] == $categoria['CAT_IN_ID']?"selected":""?>><?php echo $categoria['CAT_ST_DESCRICAO']?></option>
                    <?php endforeach;?>
               </select>
            </div>
             <div class="form-group">
               <label for="MOV_DT_EMISSAO">Data de Emissão:</label>
               <input name="MOV_DT_EMISSAO" class="data form-control" value="<?php echo $this->row['MOV_DT_EMISSAO']?>">
            </div>
              <div class="form-group">
               <label for="dia_vencimento">Dia de Vencimento:</label>
               <input name="dia_vencimento" class="parcelas data form-control" />
            </div>
        </div>
        <div class="col-md-9">
           <div class="form-group">
               <label for="MOV_DESCRICAO">Descrição:</label>
               <textarea name="MOV_ST_DESCRICAO" class="form-control" ><?php echo $this->row['MOV_ST_DESCRICAO']?></textarea>
            </div>
            <div class="form-group">
               <label for="MOV_DBL_TOTAL">Valor:</label>
               <input name="MOV_DBL_TOTAL" id="MOV_DBL_TOTAL" class="parcelas  form-control" value="<?php echo $this->row['MOV_DBL_TOTAL']?>"/>
            </div>
            <div class="form-group">
               <label for="MOV_IN_PARCELAS">Número de Parcelas:</label>
               <input name="MOV_IN_PARCELAS" id="MOV_IN_PARCELAS" type="number" class="parcelas form-control" value="<?php echo $this->row['MOV_IN_PARCELAS']?>"/>
            </div>
        </div>
        <div class="col-md-12">
           <div id="div-parcelas">
             <div class="page-header"><h1 class="text-center">Parcelamento</h1></div>
                <div class="col-md-12">
                   <table class="table table-striped table-bordered responsive">
                      <tr class="success">
                        <td class="text-center"><b>Parcela</b></td>
                        <td class="text-center"><b>Data de Vencimento</b></td>
                        <td class="text-center"><b>Valor</b></td>
                      </tr>
                      <?php if(!empty($this->aParcela)):?>
                      <?php foreach ($this->aParcela as $parcela):?>
                         <tr>
                          <td><input type="text" class="form-control" name="PAR_IN_PARCELA[]" value="<?php echo $parcela['PAR_IN_PARCELA']?>" /></td>
                          <td><input type="text" class="form-control" name="PAR_DT_VENCIMENTO[]" value="<?php echo $parcela['PAR_DT_VENCIMENTO']?>"></td>
                          <td><input type="text" class="form-control" name="PAR_DBL_PARCELA[]" value="<?php echo $parcela['PAR_DBL_PARCELA']?>" /></td>
                         </tr>
                      <?php endforeach;?>
                      <?php endif;?>
                   </table>
                </div>
           </div>
        </div>
</div>
<div class="panel-footer">
       <div class="form-group ">
          <button type="submit" class="btn btn-success">Salvar &nbsp;<span class="glyphicon glyphicon-save"></span></button>
        <a href="<?php echo $this->baseUrl("mov-financeiro/index")?>" class="btn btn-primary">Voltar &nbsp;<span class="glyphicon glyphicon-arrow-left"></span></a>
       </div>
</div>
</div>
</form>
</div>
<script>
$(function(){
 $("#input-tipo").on('change',function(){
      $("#div-categoria").load("<?php echo $this->baseUrl("mov-financeiro/listar-categoria-por-tipo/CAT_IN_ID/".$this->row['CAT_IN_ID']."/CAT_CH_TIPO/")?>"+$(this).val());
  });
     $(".parcelas").on('keyup change',function(){
      $("#div-parcelas").load("<?php echo $this->baseUrl("parcelamento/gerar-parcelas?")?>"+ $("form").serialize());
     });
   });
</script>