  <div class="page-header"><h1 align="center">Lista de Movimentos Financeiros<h1></div>
        <div class="col-lg-4">
         <a class="btn btn-warning" href="<?php echo $this->baseUrl("mov-financeiro/formulario")?>">
            Novo Movimento Financeiro
            <span class="glyphicon glyphicon-plus"></span>
         </a>
        </div> 
        <br />    
        <br />           
               
            <table class="table table-bordered table-hover">
            
            <tr class="text-center success">
             <td><b>Ações</b></td>
                <td><b>ID</b></td>
                <td><b>Tipo de Movimento</b></td>
                <td><b>Categoria</b></td>
                <td><b>Situação</b></td>
                <td><b>Parcelas</b></td>
            </tr>
        <?php if(sizeof($this->paginator)): ?>
            <?php foreach($this->paginator as $movimento){ ?>
            <tr>
                <td class="text-center">
                    <a class="btn btn-primary" title="Editar" href="<?php echo $this->baseUrl("mov-financeiro/formulario/MOV_IN_ID/").$this->escape($movimento->MOV_IN_ID)?>"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-danger" title="Excluir" href="<?php echo $this->baseUrl("mov-financeiro/excluir/MOV_IN_ID/").$this->escape($movimento->MOV_IN_ID)?>"><span class="glyphicon glyphicon-remove"></span></a>                </td>
                <td class="text-center"><?php echo $this->escape($movimento->MOV_IN_ID); ?></td>
                <td class="text-center"><?php echo $this->escape($movimento->MOV_CH_TIPO); ?></td>
                <td class="text-center"><?php echo $this->escape($movimento->CAT_ST_DESCRICAO); ?></td>
                <td class="text-center"><?php echo $this->escape($movimento->MOV_CH_SITUACAO); ?></td>
                <td class="text-center"><?php echo $this->escape($movimento->MOV_IN_PARCELAS); ?></td>
            </tr>    
                <?php } ?>
            
            </table>
        <?php else: ?>
            <li>Nenhum Banco encontrado.</li>
        <?php endif; ?>
        </ul>
        <?php echo $this->paginator; ?>
